// const { Category } = require('../model/Category');
// const { User } = require('../model/User');


exports.fetchUserById = async (req, res) => {
  const companies = [
    "Apple",
    "Microsoft",
    "Amazon",
    "Google",
    "Meta",
    "Tesla",
    "Samsung",
    "Intel",
    "IBM",
    "Oracle",
    "Adobe",
    "Salesforce",
    "Cisco",
    "Netflix",
    "NVIDIA",
    "HP",
    "Dell",
    "Uber",
    "Airbnb",
    "Spotify",
    "PayPal",
    "Shopify",
    "Square",
    "Snapchat",
    "Twitter",
    "Pinterest",
    "Reddit",
    "Dropbox",
    "Zoom",
    "Slack",
    "Lyft",
    "TikTok",
    "Baidu",
    "Alibaba",
    "Tencent",
    "ByteDance",
    "LinkedIn",
    "eBay",
    "Qualcomm",
    "AMD",
    "Samsung Electronics",
    "Foxconn",
    "Sony",
    "Panasonic",
    "LG",
    "Xiaomi",
    "Huawei",
    "ZTE",
    "Nokia",
    "Ericsson",
    "Walmart",
    "Target",
    "Costco",
    "Home Depot",
    "IKEA",
    "PepsiCo",
    "Coca-Cola",
    "Unilever",
    "Procter & Gamble",
    "Nestle",
    "Johnson & Johnson",
    "Pfizer",
    "Moderna",
    "AstraZeneca",
    "Merck",
    "Novartis",
    "Roche",
    "GlaxoSmithKline",
    "Biogen",
    "General Motors",
    "Ford",
    "Toyota",
    "Volkswagen",
    "BMW",
    "Mercedes-Benz",
    "Ferrari",
    "Porsche",
    "Rolls Royce",
    "SpaceX",
    "Blue Origin",
    "Boeing",
    "Lockheed Martin",
    "Northrop Grumman",
    "Raytheon",
    "Caterpillar",
    "3M",
    "Honeywell",
    "Siemens",
    "General Electric",
    "ExxonMobil",
    "Chevron",
    "Shell",
    "BP",
    "TotalEnergies",
    "Saudi Aramco",
    "Schlumberger",
    "Accenture",
    "Deloitte",
    "McKinsey",
    "Boston Consulting Group",
    "PwC",
    "KPMG"
  ];
  
  
};

exports.updateUser = async (req, res) => {
  // const { id } = req.params;
  // try {
  //   const user = await User.findByIdAndUpdate(id, req.body, { new: true });
  //   res.status(200).json(user);
  // } catch (err) {
  //   res.status(400).json(err);
  // }
};